language: csharp
mono: none
dotnet: 2.0.0
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then rvm use 2.3.1; ulimit -n 1024; fi
before_script:
  - make build
script:
 - make test
