version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install build-essential
      - run: make build
      - run: make test
